### ISSUE TITLE
pip3 install vllm-pascal

### ISSUE THREAD

**Issue by Molocks** [sasha0552/pascal-pkgs-ci#1]
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by sasha0552** [comment]
Hi. It looks like you are unable to connect to PyPI. vLLM requires some dependencies from PyPI, so you must have access to both PyPI and GitHub to successfully install the package. Check your network connection, proxy settings, etc.
