### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by Molocks** [sasha0552/pascal-pkgs-ci#2]
hello my dear friends,when i install triton i met this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.4.0 requires triton==3.0.0; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13", but you have triton 0.0.0 which is incompatible.

**Comment by sasha0552** [comment]
Hi. You need to install `torch` BEFORE `triton`. This usually means that you need to install the dependencies of the target project first, unless you are developing the project from scratch.
