### ISSUE TITLE
Triton error

### ISSUE THREAD

**Issue by cduk** [sasha0552/pascal-pkgs-ci#5]
I just did `docker pull ghcr.io/sasha0552/vllm` and tried to launch `Satwik11/Llama-3.3-70B-Instruct-AutoRound-GPTQ-4bit` on 4xP100 with -tp 4

I got the error message: 

```
multiproc_worker_utils.py:236]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/scheduler.py", line 3348, in create_backend
ESC[1;36m(VllmWorkerProcess pid=62)ESC[0;0m ERROR 12-26 16:20:28 multiproc_worker_utils.py:236]     raise RuntimeError(
ESC[1;36m(VllmWorkerProcess pid=62)ESC[0;0m ERROR 12-26 16:20:28 multiproc_worker_utils.py:236] RuntimeError: Found Tesla P100-PCIE-16GB which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.0
```

I wasn't sure if there was a workaround for this or if I need to patch triton (I assumed the docker image would have required patches already). I tried also --enforce-eager flag, but still got the error.

**Comment by sasha0552** [comment]
Hi!

This is not a triton error, but a pytorch error. It looks like vLLM started using the pytorch inductor api.

I tried to fix this error. Could you retest when the build is ready? (you can check the status on the “Actions” tab)

**Comment by cduk** [comment]
No joy. Tried with --enforce-eager on and off.

File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at https://github.com/openai/triton

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by sasha0552** [comment]
Should be fixed with [this](https://github.com/sasha0552/pascal-pkgs-ci/actions/runs/12527437276) build.

Ref: vllm-project/vllm#11584

**Comment by cduk** [comment]
Thanks. I confirmed it is now loading and working.

**Comment by sasha0552** [comment]
Ref: pytorch/pytorch#143956
